export const ROUTES = {
    LOGIN: "/login",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    VERIFY_EMAIL: "/verify-email",
    PROFILE: "/profile",
    COURSE_CATEGORIES: "/course-categories",
    COURSE_DETAIL: (courseId) => `/courses/${courseId}`,
    PAYMENT: "/payment",
    TUTORS: "/tutors",
    TUTOR_DETAIL: (tutorId) => `/tutors/${tutorId}`,
    ABOUT: "/about",
    DOCS: "/docs",
    JOIN_TEAM: "/join-team",
    
    ADMIN_DASHBOARD: "/admin/dashboard",
    ADMIN_USERS: "/admin/users",
    ADMIN_USER_CREATE: "/admin/users/create",
    ADMIN_CATEGORIES: "/admin/categories",
    ADMIN_COURSES: "/admin/courses",
    ADMIN_TUTORS: "/admin/tutors",
    ADMIN_TUTOR_APP: "/admin/applications",
    ADMIN_REVIEWS: "/admin/reviews",
    ADMIN_ENROLLMENTS: "/admin/enrollments",
    ADMIN_COURSE_SUGGESTIONS: "/admin/course-suggestions",
    ADMIN_COURSE_DETAIL: (courseId) => `/admin/courses/${courseId}`,
};